name: $PROJECT

networks:
  proxy:

services:
  next:
    image: $PROJECT:next
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
      target: install
    command: bun run dev
    env_file: .env
    volumes:
      - ./:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`$CNAME`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.routers.web.service=web
      - traefik.http.services.web.loadbalancer.server.port=3000
    networks:
      - proxy

  traefik:
    image: traefik:latest
    command:
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedbydefault=false
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.$CNAME`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
    networks:
      proxy:
        aliases:
          - $CNAME
    depends_on:
      - next
